### PR TITLE
Capture filter translation with context 

### PR DESCRIPTION
**Pull request by skrajewski**
Hi,

this PR provides support for context used in `translate` filter, e.g. `{{ 'Hello' | translate: 'context' }}`

Kind regards

p.s. Duplicate of #104 #155

### CODE REVIEW

**Comment by joh-klein** [comment]
I would love to have this feature. What is missing here?

**Comment by skrajewski** [comment]
@rubenv, any chance to merge this feature into next release?

**Comment by rubenv** [comment]
Merged, don't know why this wasn't in yet. Apologies for the late reply, I've been out travelling.

**Comment by rubenv** [comment]
Released to NPM as `v2.3.1`. Thanks!

**Comment by skrajewski** [comment]
Many thanks!

**Pull request merged**
