### PR TITLE
mkAttrRegex fixed hard coded string

### PR DESCRIPTION
**Pull request by cxminer**
mkAttrRegex has a hard coded string "translate" in regex, I've replaced it with the "attribute", also the function did not make use of custom options attribute.

### CODE REVIEW

**Comment by rubenv** [comment]
Could you add a test case for this functionality?

Without a regression test there's no guarantee that this'll keep working in the future, which would be a shame.

**Comment by cxminer** [comment]
Will do as soon as I get the time.

**Comment by cxminer** [comment]
I think that should do it.

**Comment by rubenv** [comment]
Looks great! Thanks a lot, merging + pushing release.

**Comment by rubenv** [comment]
Pushed new releases (`2.1.12`) for `angular-gettext-tools` and `grunt-angular-gettext`.

**Pull request merged**
