### PR TITLE
Support TypeScript

### PR DESCRIPTION
**Pull request by tabe1hands**

### CODE REVIEW

**Comment by rubenv** [comment]
I'm not sure about this. My policy on transpiled languages has always been that it's better to work on the output of transpilation, rather than adding each and every dependency.

Then again, TypeScript isn't exactly obscure and there's great value in having correct references in the `.po` files.

**Comment by circlingthesun** [comment]
Typescript support would be greatly appreciated :)

**Comment by rhuitl** [comment]
I'm also very interested in this, running angular-gettext-tools on the minified and chunked output of a webpack project (that possibly also includes other JS dependencies) does not sound too intriguing.

If you are concerned about the extra TS dependency requried to use angular-gettext-tools, maybe we can create a angular-gettext-tools-ts fork of this project?

If you're not going to merge this, I could look into ways to extract the TS compiler output (still single files hopefully) from the Webpack build process and use those for angular-gettext-tools.

**Comment by rubenv** [comment]
> If you're not going to merge this

Just didn't have the time yet to look into this.

Let's do it now!

**Comment by rubenv** [comment]
Published as `v2.3.4`

**Comment by rubenv** [comment]
Thanks a lot!

**Comment by rhuitl** [comment]
Cool thank you, working nicely :)

**Pull request merged**
