### PR TITLE
Change RegExp for extract strings in nested filter

### PR DESCRIPTION
**Pull request by fontsie**
es. {{ $scope.myString || ('defaultString' | translate) }}

### CODE REVIEW

**Comment by rubenv** [comment]
Interesting!

This breaks some of our test cases, so it needs some work.

Also: could you please add a test case that illustrates the new behavior (in other words: a test case that fails without these changes). I don't accept changes like these unless they're illustrated by a good test case, otherwise there's no way to ensure we don't accidentally break it in the future.

**Comment by fontsie** [comment]
Hi! Can you check if everything is ok?

**Comment by rubenv** [comment]
Looks good to me, merging!

**Comment by rubenv** [comment]
Released to NPM as `2.1.8`. Thanks!

**Comment by rubenv** [comment]
I had to revert this: it breaks extraction of strings for some of the cases we're seeing in one of our projects. Working on a test case right now.

**Comment by rubenv** [comment]
Just pushed a test case that fails with the code from this pull request (and worked fine previously).

```
  1) Extract (multi-line HTML) Issue 122:

      AssertionError: 'text-align\': col.align }">{{row[col.id]}}</td></tr></tbody></table><div ng-if="options.type == \'table\' &amp;&amp; options.da == 'No data'
      + expected - actual

      -text-align': col.align }">{{row[col.id]}}</td></tr></tbody></table><div ng-if="options.type == 'table' &amp;&amp; options.data.rows.length == 0" class="panel-body"><div class="vis"><svg width="100%" height="100" class="chart"><g width="100%" height="100%" class="nodata"><text text-anchor="middle" x="50%" y="50%" display="inherit">{{'No data
      +No data
      
      at assertString (test/extract_multiline.js:26:20)
      at Context.<anonymous> (test/extract_multiline.js:35:9)
```

This is probably an easy fix (a matter of swapping greedy/ungreedy somewhere).

Rolling a new release without the changes from this pull request.

**Pull request merged**
