### PR TITLE
Fix #84: Replace esprima with espree for ES6 support

### LINKED ISSUE #84: Esprima is out of date - esprima 2 is released, and it supports ES6.
Now I can't directly extract text from es6 scripts

### PR DESCRIPTION
**Pull request by smehrbrodt**

### CODE REVIEW

**Comment by rubenv** [comment]
Could you also add a test case with an ES6 file that didn't work previously?

**Comment by smehrbrodt** [comment]
Is that test ok or do you need more tests?

**Comment by rubenv** [comment]
Nope, looks great.

@gabegorelick Are you cool with merging this? I'm guessing a switch to espree won't impact the gulp plugin.

**Comment by gabegorelick** [comment]
I would bump the major version just to be safe. It's a pretty big change
and adds a significant amount of functionality (the ability to work with
es6 code).

**Comment by rubenv** [comment]
@gabegorelick Major as in 3.0? Or rather 2.1.0?

**Comment by gabegorelick** [comment]
3.0. It should be an opt in process for existing users to get es6 parsing.
Although I'm probably being pessimistic in terms of what could break.

**Comment by rubenv** [comment]
@gabegorelick 3.0 is a bit of a big bump for something that should be completely compatible, no?

**Comment by gabegorelick** [comment]
Yeah maybe you're right.

**Comment by rubenv** [comment]
Tagged as "v2.1.0".

I'll be releasing an update grunt-angular-gettext in a minute.

@smehrbrodt Thanks a lot!

**Pull request merged**
