### PR TITLE
Changes default sourceType of js extraction from 'script' to 'module'…

### PR DESCRIPTION
**Pull request by IShotTheSheriff**
…. It fixes issue #144 with parsing ES6 code.

### CODE REVIEW

**Comment by rubenv** [comment]
Could you add a unit test that demonstrates why this is needed? Just to make sure we don't break it again in the future.

**Comment by sbrandtb** [comment]
I tried locally. It may fix the issues you mentioned regarding imports, but it doesn't solve the issues with using double colons

**Comment by IShotTheSheriff** [comment]
@rubenv sure I've just added test cases for both export and import features of ES6.
@sbrandtb yea I was targeting only import/export problem as it stopped whole files from being parsed. I can try to fix double colons issue in another PR if you can provide me with some example of what's wrong.

**Comment by rubenv** [comment]
Excellent patch! Merged.

**Comment by rubenv** [comment]
Release `v2.2.2` of angular-gettext-tools and grunt-angular-gettext.

Thanks a lot @IShotTheSheriff!

**Pull request merged**
